service: fb-clone-backend-lambda
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    MONGO_URI: ${file(env.yml):MONGO_URI}
    LAMBDA_MODE: 1
functions:
  graphql:
    handler: backend.handler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true
